### ISSUE TITLE
Reddit crawler proposal

### ISSUE THREAD

**Issue by brenoc** [NAMD/mediacloud_backend#83]
I'm opening this issue to discuss how the Reddit crawler should work. 

As suggested by @fccoelho, we'll be using [PRAW](https://praw.readthedocs.org/en/v3.1.0/).

The Reddit's API gives the following JSON for a link posted on Reddit: https://github.com/reddit/reddit/wiki/JSON#link-implements-votable--created

I think we could store on mediacloud the properties: 
- `author`: the account name of the poster. null if this is a promotional link
- `title`: the title of the link. may contain newlines for some reason
- `permalink`: relative URL of the permanent link for this link
- `score`: the net-score of the link
- `subreddit`: subreddit of thing excluding the /r/ prefix. "pics"
- `url`: the link of this post. the permalink if this is a self-post 

Should we keep self posts too? If we do, we have to store `selftext` or `selftext_html` property.

I think we could start only crawling the front page of Reddit. What do you think?

**Comment by fccoelho** [comment]
I think we should only keep self posts if they give us information we wouldn't get otherwise.

@flavioamieiro, do you think we can start developing the new crawlers as celery tasks? We already have a celery app in the backend that we use for indexing, right?

**Comment by flavioamieiro** [comment]
I think we should definitely use celery for our crawlers. mediacloud_backend still doesn't use it, though. We've been planning to use it  to upload documents to pypln and to get their analysis back, but this was delayed due to other tasks.

I've created a [gist with really simple code for a celery task to upload documents to pypln](https://gist.github.com/flavioamieiro/101d3da4c2a3550a224d), this may be useful as a reference. There's also the NAMD/pypln.backend implementation, which is using celery in a (slightly) more complex way.

About self posts: I think keeping them is somewhat analogous to keeping other social media (facebook, twitter etc) posts. They may be useful, but we need to understand them before we use them in our analysis, specially because the kind of posts you'll see will change a lot depending on the subreddit in question. Maybe we store them separately?

One more thing I would say is that we probably need some kind of heuristics to skip some content, such as videos and images. A lot of the most popular posts on reddit will point to a video (usually on youtube.com) or an image (usually on imgur.com). I think these posts are really not interesting for us, since there's not really any text content there.

I think starting with the front page may be a good idea, but if we are targeting content in Portuguese we may need to start somewhere else (maybe /r/Brasil?).

**Comment by fccoelho** [comment]
I agree with @flavioamieiro points. Regarding the Brasil subreddit, it's important, but with this crawler, we should not shy away from English language posts. I see this as a good opportunity to start tackling other languages.

**Comment by brenoc** [comment]
Do you know any NAMD code that this crawler could be based on? I have to read more on Celery though.

Just for the sake of simplicity I'll start with [/r/brasil](http://www.reddit.com/r/brasil) passing to pypln, then I'll move to the reddit front-page.

**Comment by flavioamieiro** [comment]
I don't think we have any code quite like that. The only place we're actually using celery for now is in [pypln.backend](https://github.com/namd/pypln.backend/). I've also [created a gist with an example of how to send files to PyPLN using celery](https://gist.github.com/flavioamieiro/101d3da4c2a3550a224d). But I think basically there should be at least celery task for url discovery, and another one to actually get the content from the pages.

**Comment by fccoelho** [comment]
Hi @brenoc, if you want to start the implementation with just a crawler function, we can later turn it into a celery task, it is just a matter of decorating it. @flavioamieiro , perhaps we should start a celery app in a separate issue as it will end up being used by all crawlers, hopefully.

**Comment by flavioamieiro** [comment]
@fccoelho I agree that doing the work outside of celery and then turning it into a celery task may be a good idea. 

I had started a celery app on mediacloud_backend, but stopped working on it for other reasons. I'll try to add it again as soon as possible.
